package in.com.app.wsdl;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 11/7/2013 11:45:15 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import java.util.Hashtable;
import java.util.Vector;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapPrimitive;

import android.util.Base64;

public class VectorByte extends Vector<Byte> implements KvmSerializable {
    
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public VectorByte(){}
    
    public VectorByte(SoapPrimitive soapPrimitive) {
        if (soapPrimitive != null) {
            String result = soapPrimitive.toString();
            if (result != "") {
                byte[] bytes = Base64.decode(result, Base64.DEFAULT);
                for (final byte b : bytes) {
                    add(b);
                }
            }
        }
    }
    public VectorByte(byte[] bytes){
        for (byte b : bytes) {
            add(b);
        }
    }
    @Override
    public Object getProperty(int arg0) {
        return this.get(arg0);
    }
    
    @Override
    public int getPropertyCount() {
        return this.size();
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        info.name = "Byte";
        info.type = Byte.class;
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
    @Override
    public String toString() {
        byte[] byteToString = toBytes();
        return Base64.encodeToString(byteToString, Base64.DEFAULT);
    }
    public byte[] toBytes(){
        byte[] bytes = new byte[this.size()];
        int i = 0;
        for (Byte b : this) {
            bytes[i++] = b;
        }
        return bytes;
    }
}
